Feature/#6
Proj-TRENDAR/Frontend pull request #10
Opened 2023-12-04 00:49 UTC by bkks1004

[로그인 페이지 구현](https://github.com/Proj-TRENDAR/Frontend/issues/6)

2023-12-09 16:56 UTC, Ryusoo-h requested changes

2023-12-09 16:56 UTC, Ryusoo-h commented on src/pages/Login/index.tsx
> +            </Button>
트렌더 살펴보기가 페이지이기에 button태그보다는 a태그가 마크업에 적절하다고 생각하는데..
`Button`컴포넌트와 같은 모양이지만 Link(a태그)로 출력되는 `LinkButton` 컴포넌트를 만드는건 어떨까요?

페이지 이동시 사용하는 버튼 =>  `LinkButton`컴포넌트 사용
그 외, 폼 전송 등을 위한 버튼 =>  기존 `Button`컴포넌트 사용

2023-12-12 12:54 UTC, bkks1004 commented on src/pages/Login/index.tsx
> +            </Button>
링크로 이동되기때문에 a tag가 적절하다고 생각하시는거죠??  
Link button이 버튼안에 a tag를 넣어서 연결시키는걸 말씀하시는 것 맞을까요??

2023-12-14 16:07 UTC, Ryusoo-h commented on src/pages/Login/index.tsx
> +            </Button>
아뇻.. LinkButton은 `<Link></Link>` 태그로만들고(리액트에서 a태그 대신 Link태그 사용하니까요)
Button은 `<button></button>` 태그로 만들어야한다고 생각했어요

그래야 페이지이동은 `a`태그로, 입력 등은 `button`태그로 마크업될테니까요..
저는 항상 이렇게 해왔는데 혹시 다른 선호하는 방법이 있으신가요?

2023-12-19 10:40 UTC, bkks1004 commented on src/pages/Login/index.tsx
> +            </Button>
저는 보통 button에 route 태워서 했었어요  
말씀하신 대로 수정해볼게요

2024-03-05 16:16 UTC, merged